api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "${DOMAIN}"
            sans:
              - "${CODE_SUBDOMAIN}.${DOMAIN}"
              - "${FIREFLY_SUBDOMAIN}.${DOMAIN}"
              - "${TRAEFIK_SUBDOMAIN}.${DOMAIN}"
              - "${VAULTWARDEN_SUBDOMAIN}.${DOMAIN}"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  cloudflare:
    acme:
      email: "${EMAIL}"
      storage: "/etc/traefik/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
